FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["BlazorApp2_WebAssembly/BlazorApp2_WebAssembly.csproj", "BlazorApp2_WebAssembly/"]
RUN dotnet restore "BlazorApp2_WebAssembly/BlazorApp2_WebAssembly.csproj"
COPY . .
WORKDIR "/src/BlazorApp2_WebAssembly"
RUN dotnet build "BlazorApp2_WebAssembly.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "BlazorApp2_WebAssembly.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BlazorApp2_WebAssembly.dll"]
